// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWKjVM6PR70nIVkRlIfztrViE3Ada5FRQ',
    appId: '1:229960052686:web:ca3bc60cf500a6d929059f',
    messagingSenderId: '229960052686',
    projectId: 'brew-crew-15e0a',
    authDomain: 'brew-crew-15e0a.firebaseapp.com',
    storageBucket: 'brew-crew-15e0a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZe7YSDI4ieG6a3ZLBObnY-jArUXgKQG8',
    appId: '1:229960052686:android:4a01274cb710281f29059f',
    messagingSenderId: '229960052686',
    projectId: 'brew-crew-15e0a',
    storageBucket: 'brew-crew-15e0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3_N5yJoZuUXpbiAxkdnBTvClkHhz_NcE',
    appId: '1:229960052686:ios:abab8845781afa4229059f',
    messagingSenderId: '229960052686',
    projectId: 'brew-crew-15e0a',
    storageBucket: 'brew-crew-15e0a.appspot.com',
    iosBundleId: 'com.example.brewCrew',
  );
}
